//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="LegoMazeDriver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=1943a4600bc69186" +
    "")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.AllowPartiallyTrustedCallersAttribute()]

namespace Robotics.Services.LegoMazeDriver.Proxy {
    
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", ElementName="LegoMazeDriverState")]
    public class LegoMazeDriverState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public LegoMazeDriverState() {
        }
        
        private bool _MotorEnabled;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public bool MotorEnabled {
            get {
                return this._MotorEnabled;
            }
            set {
                this._MotorEnabled = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current LegoMazeDriverState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState typedTarget = ((global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState)(target));
            typedTarget._MotorEnabled = this._MotorEnabled;
        }
        
        /// <summary>
        ///Clones LegoMazeDriverState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState target0 = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current LegoMazeDriverState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._MotorEnabled);
        }
        
        /// <summary>
        ///Deserializes LegoMazeDriverState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized LegoMazeDriverState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._MotorEnabled = reader.ReadBoolean();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", ElementName="StopRequest")]
    public class StopRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public StopRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current StopRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest typedTarget = ((global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest)(target));
        }
        
        /// <summary>
        ///Clones StopRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest target0 = new global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current StopRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes StopRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized StopRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", ElementName="ForwardRequest")]
    public class ForwardRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ForwardRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current ForwardRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest typedTarget = ((global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest)(target));
        }
        
        /// <summary>
        ///Clones ForwardRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest target0 = new global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ForwardRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes ForwardRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ForwardRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", ElementName="BackwardRequest")]
    public class BackwardRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public BackwardRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current BackwardRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest typedTarget = ((global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest)(target));
        }
        
        /// <summary>
        ///Clones BackwardRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest target0 = new global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current BackwardRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes BackwardRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized BackwardRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", ElementName="TurnLeftRequest")]
    public class TurnLeftRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public TurnLeftRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current TurnLeftRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest typedTarget = ((global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest)(target));
        }
        
        /// <summary>
        ///Clones TurnLeftRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest target0 = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current TurnLeftRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes TurnLeftRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized TurnLeftRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", ElementName="TurnRightRequest")]
    public class TurnRightRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public TurnRightRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current TurnRightRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest typedTarget = ((global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest)(target));
        }
        
        /// <summary>
        ///Clones TurnRightRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest target0 = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current TurnRightRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes TurnRightRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized TurnRightRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Get : global::Microsoft.Dss.ServiceModel.Dssp.Get<global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType, global:: Microsoft.Ccr.Core.PortSet<global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState, global:: W3C.Soap.Fault>> {
        
        public Get() {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body) {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, global::Microsoft.Ccr.Core.PortSet<global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Replace : global::Microsoft.Dss.ServiceModel.Dssp.Replace<global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault>> {
        
        public Replace() {
        }
        
        public Replace(global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState body) : 
                base(body) {
        }
        
        public Replace(global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Stop : global::Microsoft.Dss.ServiceModel.Dssp.Submit<global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault>> {
        
        public Stop() {
        }
        
        public Stop(global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest body) : 
                base(body) {
        }
        
        public Stop(global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Forward : global::Microsoft.Dss.ServiceModel.Dssp.Submit<global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault>> {
        
        public Forward() {
        }
        
        public Forward(global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest body) : 
                base(body) {
        }
        
        public Forward(global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Backward : global::Microsoft.Dss.ServiceModel.Dssp.Submit<global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault>> {
        
        public Backward() {
        }
        
        public Backward(global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest body) : 
                base(body) {
        }
        
        public Backward(global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class TurnLeft : global::Microsoft.Dss.ServiceModel.Dssp.Submit<global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault>> {
        
        public TurnLeft() {
        }
        
        public TurnLeft(global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest body) : 
                base(body) {
        }
        
        public TurnLeft(global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class TurnRight : global::Microsoft.Dss.ServiceModel.Dssp.Submit<global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault>> {
        
        public TurnRight() {
        }
        
        public TurnRight(global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest body) : 
                base(body) {
        }
        
        public TurnRight(global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class LegoMazeDriverOperations : global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup, global:: Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop, global:: Robotics.Services.LegoMazeDriver.Proxy.Get, global:: Robotics.Services.LegoMazeDriver.Proxy.Replace, global:: Robotics.Services.LegoMazeDriver.Proxy.Stop, global:: Robotics.Services.LegoMazeDriver.Proxy.Forward, global:: Robotics.Services.LegoMazeDriver.Proxy.Backward, global:: Robotics.Services.LegoMazeDriver.Proxy.TurnLeft, global:: Robotics.Services.LegoMazeDriver.Proxy.TurnRight> {
        
        public LegoMazeDriverOperations() {
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup() {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop() {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState, global:: W3C.Soap.Fault> Get() {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            global::Robotics.Services.LegoMazeDriver.Proxy.Get operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(out global::Robotics.Services.LegoMazeDriver.Proxy.Get operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState, global:: W3C.Soap.Fault> Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.Get operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, out global::Robotics.Services.LegoMazeDriver.Proxy.Get operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault> Replace() {
            global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState body = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState();
            global::Robotics.Services.LegoMazeDriver.Proxy.Replace operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Replace(out global::Robotics.Services.LegoMazeDriver.Proxy.Replace operation) {
            global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState body = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault> Replace(global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState body) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.Replace operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Replace(global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState body, out global::Robotics.Services.LegoMazeDriver.Proxy.Replace operation) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> Stop() {
            global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest();
            global::Robotics.Services.LegoMazeDriver.Proxy.Stop operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Stop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Stop(out global::Robotics.Services.LegoMazeDriver.Proxy.Stop operation) {
            global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Stop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> Stop(global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest body) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.Stop operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Stop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Stop(global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest body, out global::Robotics.Services.LegoMazeDriver.Proxy.Stop operation) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Stop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> Forward() {
            global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest();
            global::Robotics.Services.LegoMazeDriver.Proxy.Forward operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Forward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Forward(out global::Robotics.Services.LegoMazeDriver.Proxy.Forward operation) {
            global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Forward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> Forward(global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest body) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.Forward operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Forward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Forward(global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest body, out global::Robotics.Services.LegoMazeDriver.Proxy.Forward operation) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Forward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> Backward() {
            global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest();
            global::Robotics.Services.LegoMazeDriver.Proxy.Backward operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Backward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Backward(out global::Robotics.Services.LegoMazeDriver.Proxy.Backward operation) {
            global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Backward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> Backward(global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest body) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.Backward operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Backward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Backward(global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest body, out global::Robotics.Services.LegoMazeDriver.Proxy.Backward operation) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.Backward(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> TurnLeft() {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest();
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice TurnLeft(out global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft operation) {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> TurnLeft(global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest body) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice TurnLeft(global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest body, out global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft operation) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeft(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> TurnRight() {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest();
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice TurnRight(out global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight operation) {
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest();
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultSubmitResponseType, global:: W3C.Soap.Fault> TurnRight(global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest body) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest();
            }
            global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice TurnRight(global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest body, out global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight operation) {
            if ((body == null)) {
                body = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest();
            }
            operation = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRight(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    [global::System.ComponentModel.DescriptionAttribute("This tutorial demonstrates how to create a service that partners with abstract, b" +
        "ase definitions of hardware services.")]
    [global::System.ComponentModel.DisplayNameAttribute("(User) Robotics Tutorial 4 (C#): Drive-By-Wire")]
    public class Contract {
        
        public const string Identifier = "http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html";
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="service">service path</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, string service, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", service);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", null);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
    }
    
    public class CombinedOperationsPort : global::Microsoft.Dss.Core.DssCombinedOperationsPort {
        
        public CombinedOperationsPort() {
            this.LegoMazeDriverOperations = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverOperations();
            base.Initialize(new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.LegoMazeDriverOperations, "http://schemas.microsoft.com/robotics/2006/06/roboticstutorial4.user.html", "LegoMazeDriverOperations", ""));
        }
        
        public global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverOperations LegoMazeDriverOperations;
    }
}
