//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="LegoMazeDriver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=1943a4600bc69186" +
    "")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.AllowPartiallyTrustedCallersAttribute()]

namespace Dss.Transforms.TransformLegoMazeDriver {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_Proxy_LegoMazeDriverState_TO_Robotics_Services_LegoMazeDriver_LegoMazeDriverState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.Services.LegoMazeDriver.LegoMazeDriverState), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_LegoMazeDriverState_TO_Robotics_Services_LegoMazeDriver_Proxy_LegoMazeDriverState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_Proxy_StopRequest_TO_Robotics_Services_LegoMazeDriver_StopRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.Services.LegoMazeDriver.StopRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_StopRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_StopRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_Proxy_ForwardRequest_TO_Robotics_Services_LegoMazeDriver_ForwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.Services.LegoMazeDriver.ForwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_ForwardRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_ForwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_Proxy_BackwardRequest_TO_Robotics_Services_LegoMazeDriver_BackwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.Services.LegoMazeDriver.BackwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_BackwardRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_BackwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_Proxy_TurnLeftRequest_TO_Robotics_Services_LegoMazeDriver_TurnLeftRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.Services.LegoMazeDriver.TurnLeftRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_TurnLeftRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_TurnLeftRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_Proxy_TurnRightRequest_TO_Robotics_Services_LegoMazeDriver_TurnRightRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.Services.LegoMazeDriver.TurnRightRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_Services_LegoMazeDriver_TurnRightRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_TurnRightRequest));
        }
        
        public static object Robotics_Services_LegoMazeDriver_Proxy_LegoMazeDriverState_TO_Robotics_Services_LegoMazeDriver_LegoMazeDriverState(object transformFrom) {
            global::Robotics.Services.LegoMazeDriver.LegoMazeDriverState target = new global::Robotics.Services.LegoMazeDriver.LegoMazeDriverState();
            global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState from = ((global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState)(transformFrom));
            target.MotorEnabled = from.MotorEnabled;
            return target;
        }
        
        public static object Robotics_Services_LegoMazeDriver_LegoMazeDriverState_TO_Robotics_Services_LegoMazeDriver_Proxy_LegoMazeDriverState(object transformFrom) {
            global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState target = new global::Robotics.Services.LegoMazeDriver.Proxy.LegoMazeDriverState();
            global::Robotics.Services.LegoMazeDriver.LegoMazeDriverState from = ((global::Robotics.Services.LegoMazeDriver.LegoMazeDriverState)(transformFrom));
            target.MotorEnabled = from.MotorEnabled;
            return target;
        }
        
        private static global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest _cachedInstance0 = new global::Robotics.Services.LegoMazeDriver.Proxy.StopRequest();
        
        private static global::Robotics.Services.LegoMazeDriver.StopRequest _cachedInstance = new global::Robotics.Services.LegoMazeDriver.StopRequest();
        
        public static object Robotics_Services_LegoMazeDriver_Proxy_StopRequest_TO_Robotics_Services_LegoMazeDriver_StopRequest(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Robotics_Services_LegoMazeDriver_StopRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_StopRequest(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest _cachedInstance2 = new global::Robotics.Services.LegoMazeDriver.Proxy.ForwardRequest();
        
        private static global::Robotics.Services.LegoMazeDriver.ForwardRequest _cachedInstance1 = new global::Robotics.Services.LegoMazeDriver.ForwardRequest();
        
        public static object Robotics_Services_LegoMazeDriver_Proxy_ForwardRequest_TO_Robotics_Services_LegoMazeDriver_ForwardRequest(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object Robotics_Services_LegoMazeDriver_ForwardRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_ForwardRequest(object transformFrom) {
            return _cachedInstance2;
        }
        
        private static global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest _cachedInstance4 = new global::Robotics.Services.LegoMazeDriver.Proxy.BackwardRequest();
        
        private static global::Robotics.Services.LegoMazeDriver.BackwardRequest _cachedInstance3 = new global::Robotics.Services.LegoMazeDriver.BackwardRequest();
        
        public static object Robotics_Services_LegoMazeDriver_Proxy_BackwardRequest_TO_Robotics_Services_LegoMazeDriver_BackwardRequest(object transformFrom) {
            return _cachedInstance3;
        }
        
        public static object Robotics_Services_LegoMazeDriver_BackwardRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_BackwardRequest(object transformFrom) {
            return _cachedInstance4;
        }
        
        private static global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest _cachedInstance6 = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnLeftRequest();
        
        private static global::Robotics.Services.LegoMazeDriver.TurnLeftRequest _cachedInstance5 = new global::Robotics.Services.LegoMazeDriver.TurnLeftRequest();
        
        public static object Robotics_Services_LegoMazeDriver_Proxy_TurnLeftRequest_TO_Robotics_Services_LegoMazeDriver_TurnLeftRequest(object transformFrom) {
            return _cachedInstance5;
        }
        
        public static object Robotics_Services_LegoMazeDriver_TurnLeftRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_TurnLeftRequest(object transformFrom) {
            return _cachedInstance6;
        }
        
        private static global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest _cachedInstance8 = new global::Robotics.Services.LegoMazeDriver.Proxy.TurnRightRequest();
        
        private static global::Robotics.Services.LegoMazeDriver.TurnRightRequest _cachedInstance7 = new global::Robotics.Services.LegoMazeDriver.TurnRightRequest();
        
        public static object Robotics_Services_LegoMazeDriver_Proxy_TurnRightRequest_TO_Robotics_Services_LegoMazeDriver_TurnRightRequest(object transformFrom) {
            return _cachedInstance7;
        }
        
        public static object Robotics_Services_LegoMazeDriver_TurnRightRequest_TO_Robotics_Services_LegoMazeDriver_Proxy_TurnRightRequest(object transformFrom) {
            return _cachedInstance8;
        }
    }
}
